version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: redis-deduplicate-postgres
    environment:
      POSTGRES_DB: redis-deduplicate_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d redis-deduplicate_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: